<a href="postjob" id="postJobBtn">Post a job</a>

 {% for row in rows %}
 <div class="listing" id="{{ row.id }}">
 <div class="list-left">
	<h2>{{ row.job_title }} <span class="company">@ {{ row.company }}</span></h2>
	

	<p class="qualifications">Requirments: 
		{% if row.qualifications == false %}
			None
		{% else %}
			{{ row.qualifications }}
		{% endif %}
	</p>
	

	<p>Posted by: <a href="mailto:{{ row.email }}">{{row.email}}</a></p>
	<p>Salary Range: 
		{% if row.salary == false %}
			<span>None</span>

		{% else %}
			{{ row.salary }} Per Year
		{% endif %}

	</p>

	<p class="description">Description: <br /> 
	  {% if row.description == false %}
			<span>No description</span>
		{% else %}
			{{ row.description | nl2br }} 
		{% endif %}
	</p>
 </div>

 <div class="list-right">
 	<span class="type">{{ row.type }}</span>
	 
 	 <span class="date">Start Date: 

 	 	{% if row.start_date == false %}
 	 		N/A
		{% else %}
 	 		{{ row.start_date }}
		{% endif %}
 	 </span>

  <a href="apply/{{row.id}}" class="applyBtn">Apply</a>



 </div><!-- /list-right -->


</div><!-- /listing -->

{% endfor %}





